export const seedTerms = [
  {
    slug: 'blockchain',
    name: 'Blockchain',
    category: 'Core Concepts',
    short_definition: 'A distributed, immutable ledger that records transactions across a network of computers.',
    full_definition: `A blockchain is a type of distributed ledger technology (DLT) that stores data in blocks, which are linked together in a chain. Each block contains a cryptographic hash of the previous block, a timestamp, and transaction data. Once recorded, the data in any given block cannot be altered without altering all subsequent blocks, making it inherently secure and tamper-resistant. Blockchains are managed by a peer-to-peer network collectively adhering to a protocol for inter-node communication and validating new blocks. This makes blockchains resistant to modification of their data because, once recorded, the data in any given block cannot be altered retroactively without alteration of all subsequent blocks.`,
    upvotes: 142,
    downvotes: 3,
  },
  {
    slug: 'wallet',
    name: 'Crypto Wallet',
    category: 'Wallets',
    short_definition: 'Software that stores your private and public keys, allowing you to interact with blockchains.',
    full_definition: `A cryptocurrency wallet is a digital tool that allows users to store, send, and receive cryptocurrencies. Unlike a physical wallet, a crypto wallet doesn't actually store the cryptocurrency itself — instead, it stores the public and private keys needed to access and manage your funds on the blockchain. Your public key is like your bank account number (safe to share), while your private key is like your PIN (never share it). Wallets come in several forms: hardware wallets (physical devices), software wallets (apps), and web wallets (browser extensions like MetaMask).`,
    upvotes: 98,
    downvotes: 1,
  },
  {
    slug: 'gas-fee',
    name: 'Gas Fee',
    category: 'Core Concepts',
    short_definition: 'A fee paid to compensate for the computing energy required to process transactions on Ethereum.',
    full_definition: `Gas fees are payments made by users to compensate for the computing energy required to process and validate transactions on the Ethereum blockchain. "Gas" refers to the unit that measures the amount of computational effort required to execute specific operations. Every transaction on Ethereum requires a certain amount of gas, and the total fee is calculated as: Gas Used × Gas Price. Gas prices are denominated in Gwei (a tiny fraction of ETH). When the network is congested, gas prices rise as users compete to have their transactions processed faster.`,
    upvotes: 87,
    downvotes: 2,
  },
  {
    slug: 'smart-contract',
    name: 'Smart Contract',
    category: 'Core Concepts',
    short_definition: 'Self-executing contracts with the terms directly written into code on the blockchain.',
    full_definition: `Smart contracts are self-executing contracts with the terms of the agreement directly written into lines of code. They run on a blockchain and automatically execute when predetermined conditions are met, without the need for intermediaries. For example, a smart contract could automatically release payment when a service is delivered. They are transparent, irreversible, and distributed. Ethereum was the first blockchain to support smart contracts, and they are now the foundation of DeFi, NFTs, DAOs, and most Web3 applications.`,
    upvotes: 134,
    downvotes: 4,
  },
  {
    slug: 'defi',
    name: 'DeFi',
    category: 'DeFi',
    short_definition: 'Decentralized Finance — financial services built on blockchain that operate without traditional banks.',
    full_definition: `Decentralized Finance (DeFi) refers to financial services and products built on public blockchains, primarily Ethereum. DeFi aims to recreate traditional financial systems (lending, borrowing, trading, earning interest) in a decentralized manner — without banks, brokers, or other intermediaries. Instead, smart contracts automate these functions. Key DeFi protocols include Uniswap (decentralized exchange), Aave (lending/borrowing), and Compound (interest earning). Anyone with an internet connection and a crypto wallet can access DeFi services, making it truly permissionless and open.`,
    upvotes: 210,
    downvotes: 8,
  },
  {
    slug: 'nft',
    name: 'NFT',
    category: 'NFTs',
    short_definition: 'Non-Fungible Token — a unique digital asset verified using blockchain technology.',
    full_definition: `Non-Fungible Tokens (NFTs) are unique cryptographic tokens that represent ownership of a unique item or piece of content on a blockchain. Unlike cryptocurrencies like Bitcoin (which are fungible — each coin is identical), each NFT is one-of-a-kind and cannot be replicated. NFTs can represent digital art, music, videos, virtual real estate, game items, and more. Ownership is recorded on the blockchain, providing proof of authenticity and provenance. The ERC-721 standard on Ethereum was the first NFT standard, making collections like CryptoPunks and Bored Ape Yacht Club possible.`,
    upvotes: 189,
    downvotes: 12,
  },
  {
    slug: 'staking',
    name: 'Staking',
    category: 'Staking',
    short_definition: 'Locking up cryptocurrency to support a blockchain network and earn rewards.',
    full_definition: `Staking is the process of locking up a certain amount of cryptocurrency to participate in the validation of transactions on a Proof of Stake blockchain. Stakers are chosen to create new blocks and validate transactions based on the amount of cryptocurrency they have staked. In return, they receive staking rewards — similar to earning interest in a bank. Staking is an alternative to mining (Proof of Work) and is considered more energy-efficient. Ethereum transitioned to Proof of Stake in 2022 (The Merge), requiring validators to stake 32 ETH.`,
    upvotes: 76,
    downvotes: 2,
  },
  {
    slug: 'dao',
    name: 'DAO',
    category: 'DAOs',
    short_definition: 'Decentralized Autonomous Organization — a community governed by smart contracts and token voting.',
    full_definition: `A Decentralized Autonomous Organization (DAO) is an organization represented by rules encoded as a computer program (smart contracts) that is transparent, controlled by token holders, and not influenced by a central government. DAOs enable communities to pool resources and make decisions collectively through token-based voting. Token holders can propose changes, vote on proposals, and the smart contracts automatically execute the outcomes. Examples include MakerDAO (governs the DAI stablecoin), Uniswap DAO, and Compound. DAOs represent a new model of organizational governance enabled by blockchain technology.`,
    upvotes: 92,
    downvotes: 3,
  },
  {
    slug: 'layer-2',
    name: 'Layer 2',
    category: 'Layer 2',
    short_definition: 'A secondary framework built on top of a blockchain to improve its scalability and speed.',
    full_definition: `Layer 2 (L2) refers to secondary protocols or frameworks built on top of an existing blockchain (Layer 1) to improve its scalability and transaction throughput. While Layer 1 blockchains like Ethereum provide security and decentralization, they can be slow and expensive. Layer 2 solutions process transactions off the main chain and then settle them on Layer 1, inheriting its security. Popular L2 solutions include Optimistic Rollups (Optimism, Arbitrum) and ZK-Rollups (zkSync, StarkNet). These can handle thousands of transactions per second while keeping fees extremely low.`,
    upvotes: 108,
    downvotes: 5,
  },
  {
    slug: 'bridge',
    name: 'Bridge',
    category: 'Bridges',
    short_definition: 'A protocol that enables transfer of tokens or data between two different blockchain networks.',
    full_definition: `A blockchain bridge is a protocol that allows the transfer of tokens, assets, or data between two different blockchain networks. Since different blockchains (Ethereum, Solana, Polygon, etc.) are separate ecosystems that cannot communicate natively, bridges create interoperability between them. For example, you could use a bridge to move ETH from Ethereum to Polygon to take advantage of lower fees. Bridges typically work by locking tokens on one chain and minting equivalent tokens on another. However, bridges have been a major attack vector in crypto — billions have been lost to bridge hacks.`,
    upvotes: 67,
    downvotes: 4,
  },
  {
    slug: 'liquidity-pool',
    name: 'Liquidity Pool',
    category: 'DeFi',
    short_definition: 'A collection of funds locked in a smart contract to facilitate decentralized trading.',
    full_definition: `A liquidity pool is a collection of cryptocurrency funds locked in a smart contract that provides liquidity for decentralized exchanges (DEXs). Instead of using traditional order books (buyer-seller matching), DEXs like Uniswap use Automated Market Makers (AMMs) powered by liquidity pools. Users called Liquidity Providers (LPs) deposit pairs of tokens (e.g., ETH/USDC) into pools and earn a percentage of the trading fees generated. The price of assets in the pool is determined algorithmically based on the ratio of tokens, not supply and demand orders.`,
    upvotes: 83,
    downvotes: 3,
  },
  {
    slug: 'yield-farming',
    name: 'Yield Farming',
    category: 'DeFi',
    short_definition: 'Earning rewards by providing liquidity or staking assets in DeFi protocols.',
    full_definition: `Yield farming (also called liquidity mining) is the practice of maximizing returns on cryptocurrency holdings by providing liquidity to DeFi protocols. Yield farmers move assets between different protocols to chase the highest annual percentage yield (APY). They earn returns through trading fees, interest, and governance token rewards. While yield farming can generate high returns, it comes with significant risks: smart contract vulnerabilities, impermanent loss (when the value of pooled assets diverges), and protocol exploits. The DeFi Summer of 2020 popularized yield farming, with protocols like Compound and Yearn Finance leading the way.`,
    upvotes: 71,
    downvotes: 6,
  },
  {
    slug: 'seed-phrase',
    name: 'Seed Phrase',
    category: 'Security',
    short_definition: 'A 12-24 word backup phrase that gives full access to a crypto wallet. Never share it.',
    full_definition: `A seed phrase (also called a recovery phrase or mnemonic phrase) is a series of 12 to 24 random words generated by your cryptocurrency wallet when you first set it up. This phrase is the master key to your entire wallet — it can be used to restore access to your funds on any compatible wallet if you lose your device or forget your password. The words are generated from a standardized list (BIP-39) and encode your private key in a human-readable format. The most important rule in crypto: NEVER share your seed phrase with anyone. Anyone who has it has complete control over all your assets.`,
    upvotes: 156,
    downvotes: 1,
  },
  {
    slug: 'private-key',
    name: 'Private Key',
    category: 'Security',
    short_definition: 'A secret cryptographic key that proves ownership of cryptocurrency and authorizes transactions.',
    full_definition: `A private key is a secret number (a 256-bit integer in most blockchains) that allows you to access and control your cryptocurrency. It is mathematically linked to your public key and wallet address, but cannot be reverse-engineered from them. When you sign a transaction with your private key, you're proving ownership without revealing the key itself. If someone else gets your private key, they have complete, irrevocable control over your funds — there is no "forgot my password" or customer support in crypto. Private keys are typically stored in wallets, either as a raw key or derived from a seed phrase.`,
    upvotes: 124,
    downvotes: 2,
  },
  {
    slug: 'public-key',
    name: 'Public Key',
    category: 'Security',
    short_definition: 'A cryptographic key derived from your private key, used to generate your wallet address.',
    full_definition: `A public key is a cryptographic code that allows users to receive cryptocurrency into their accounts. It is derived from your private key using one-way cryptographic functions (elliptic curve cryptography), meaning it cannot be reversed to get your private key. Your wallet address (what you share with others to receive funds) is derived from your public key via a hashing process. Public keys are safe to share — they're the crypto equivalent of your bank account number. The pairing of public and private keys is the foundation of asymmetric cryptography that secures all blockchain transactions.`,
    upvotes: 89,
    downvotes: 2,
  },
  {
    slug: 'consensus-mechanism',
    name: 'Consensus Mechanism',
    category: 'Core Concepts',
    short_definition: 'The process by which nodes in a blockchain network agree on the state of the ledger.',
    full_definition: `A consensus mechanism is the protocol that allows all nodes (computers) in a distributed blockchain network to agree on a single version of the truth — which transactions are valid and in what order they occurred. Without consensus, different nodes would have different versions of the blockchain, making it unreliable. The two main consensus mechanisms are Proof of Work (PoW), used by Bitcoin, where miners compete to solve complex puzzles; and Proof of Stake (PoS), used by Ethereum, where validators are chosen based on how much cryptocurrency they've staked. Other mechanisms include Delegated Proof of Stake (DPoS) and Proof of Authority (PoA).`,
    upvotes: 97,
    downvotes: 3,
  },
  {
    slug: 'proof-of-work',
    name: 'Proof of Work',
    category: 'Core Concepts',
    short_definition: 'A consensus mechanism where miners compete to solve cryptographic puzzles to validate transactions.',
    full_definition: `Proof of Work (PoW) is the original blockchain consensus mechanism, first introduced by Bitcoin. In PoW, network participants called miners compete to solve computationally intensive mathematical puzzles. The first miner to solve the puzzle gets to add the next block to the blockchain and receives a block reward (newly minted cryptocurrency + transaction fees). The "work" is intentionally hard to do but easy to verify — this is what makes double-spending practically impossible. PoW is extremely secure but requires massive amounts of energy. Bitcoin consumes more electricity than some countries, which has led to criticism and the development of more energy-efficient alternatives.`,
    upvotes: 103,
    downvotes: 7,
  },
  {
    slug: 'proof-of-stake',
    name: 'Proof of Stake',
    category: 'Core Concepts',
    short_definition: 'A consensus mechanism where validators are chosen based on the amount of cryptocurrency they have staked.',
    full_definition: `Proof of Stake (PoS) is an energy-efficient alternative to Proof of Work where validators are chosen to create new blocks based on how much cryptocurrency they have "staked" (locked up as collateral). Validators with more staked crypto have a higher probability of being selected to validate transactions and earn rewards. If a validator acts dishonestly, they risk losing their staked funds through "slashing." Ethereum completed its transition to PoS in September 2022 ("The Merge"), reducing its energy consumption by ~99.95%. PoS enables faster transactions and lower fees compared to PoW.`,
    upvotes: 118,
    downvotes: 4,
  },
  {
    slug: 'token',
    name: 'Token',
    category: 'Tokenomics',
    short_definition: 'A digital asset created on an existing blockchain, representing value, utility, or ownership.',
    full_definition: `In the context of blockchain, a token is a digital asset that is created and managed on an existing blockchain platform (unlike coins, which are native to their own blockchain). Tokens can represent a wide variety of things: utility tokens give access to a service, security tokens represent ownership in an asset, governance tokens allow holders to vote on protocol decisions, and stablecoins maintain a stable value. Most tokens on Ethereum follow the ERC-20 standard, which ensures compatibility across wallets and exchanges. Creating a token requires deploying a smart contract — no special mining hardware needed.`,
    upvotes: 91,
    downvotes: 2,
  },
  {
    slug: 'airdrop',
    name: 'Airdrop',
    category: 'Tokenomics',
    short_definition: 'Free distribution of cryptocurrency tokens to wallet addresses, often as a marketing strategy.',
    full_definition: `An airdrop is when a blockchain project distributes free tokens to wallet addresses, usually as part of a marketing campaign, to reward early users, or to decentralize token ownership. Airdrops can be retroactive (rewarding past users who didn't know a token would exist, like Uniswap's UNI airdrop in 2020 — worth $1,200+ at the time), or conditional (requiring users to complete tasks like following social accounts or holding certain tokens). "Airdrop farming" has become a strategy where users interact with new protocols hoping to qualify for future airdrops. Notable airdrops include Uniswap (UNI), ENS, and Optimism (OP).`,
    upvotes: 143,
    downvotes: 5,
  },
]
